Stage 3
cosmicds/hubbleds pull request #361
Opened 2024-05-07 00:38 UTC by patudom

I've added the guidelines to Stage 3 and started placing them very generically in the page layout. There are no attempts to correctly handle the state yet.

2024-05-08 22:47 UTC, patudom commented
I've added all the guidelines and wired up whatever things I could. @johnarban or @Carifio24, can one of you please review this PR and merge? Once it's merged, someone can work on adding the viewers and database connections.

2024-05-09 16:26 UTC, patudom commented
(I removed everything I could find that references "next" on the last guideline, but I'm still having issues with the off-by-1 error on the Marker list).

2024-05-09 18:36 UTC, johnarban approved these changes

2024-05-09 19:26 UTC, johnarban requested changes

2024-05-09 19:26 UTC, johnarban commented on src/hubbleds/pages/03-distance-measurements/__init__.py
> +                event_next_callback=lambda *args: component_state.transition_next(),
This I think want's to go back to the slide where we make the choice. currently this just jumps back in the marker sequence

2024-05-09 19:26 UTC, johnarban commented on src/hubbleds/pages/03-distance-measurements/__init__.py
> +                can_advance=component_state.can_transition(next=True),
```suggestion
                can_advance=False,
```

2024-05-09 19:26 UTC, johnarban commented on src/hubbleds/pages/03-distance-measurements/__init__.py
> +                can_advance=component_state.can_transition(next=True),
This can just be false, that way the user only has the buttons to press. `can_advance` acts kind of like hiding the next button

2024-05-10 17:48 UTC, johnarban approved these changes
This looks good

2024-05-10 19:00 UTC, merged